# Generated by Django 3.2.7 on 2022-03-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_chairman_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanform',
            name='selbranch',
            field=models.CharField(choices=[('Ambala', 'Ambala'), ('Amritsar', 'Amritsar'), ('Ajmerigate', 'Ajmerigate'), ('Firozepur', 'Firozepur'), ('Ghaziabad', 'Ghaziabad'), ('Jagadhari', 'Jagadhari'), ('Ludhiana', 'Ludhiana'), ('Patiala', 'Patiala'), ('Pathankot', 'Pathankot'), ('Tuglakabad ', 'Tuglakabad'), ('Head Qtrs.', 'Head Qtrs.')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='bname',
            field=models.CharField(choices=[('Ambala', 'Ambala'), ('Amritsar', 'Amritsar'), ('Ajmerigate', 'Ajmerigate'), ('Firozepur', 'Firozepur'), ('Ghaziabad', 'Ghaziabad'), ('Jagadhari', 'Jagadhari'), ('Ludhiana', 'Ludhiana'), ('Patiala', 'Patiala'), ('Pathankot', 'Pathankot'), ('Tuglakabad ', 'Tuglakabad'), ('Head Qtrs.', 'Head Qtrs.')], max_length=100),
        ),
    ]
