# Generated by Django 4.0.2 on 2022-03-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_chairman_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanform',
            name='selbranch',
            field=models.CharField(default='', max_length=50),
        ),
    ]
