# Generated by Django 4.0.2 on 2022-03-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_loanform_selbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanform',
            name='selbranch',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='branch1', max_length=50),
        ),
    ]
