# Generated by Django 4.0.2 on 2022-03-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_loanform_selbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bname',
            field=models.CharField(choices=[('Ambala', 'Ambala'), ('Amritsar', 'Amritsar'), ('Ajmerigate', 'Ajmerigate'), ('Firozepur', 'Firozepur'), ('Ghaziabad', 'Ghaziabad'), ('Jagadhari', 'Jagadhari'), ('Ludhiana', 'Ludhiana'), ('Patiala', 'Patiala'), ('Pathankot', 'Pathankot'), ('Tuglakabad ', 'Tuglakabad'), ('Head Qtrs.', 'Head Qtrs.')], max_length=100),
        ),
    ]
