# Generated by Django 3.2.7 on 2022-03-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20220316_1603'),
        ('mysite', '0013_alter_branch_bname'),
    ]

    operations = [
    ]
